/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spider2;

import java.io.IOException;
import java.util.Set;
import java.util.HashSet;
import java.util.List;
import java.util.ArrayList;
import org.jsoup.nodes.*;


public class App {
    

    private static final String HOST = "smt-stage.qa.siliconmtn.com";
    private static final int PORT_NUMBER = 443;
    
    private List<Document> docs = null;
	private Set<String> urls = null;

    
    public void crawl() {
    	Connection c = new Connection(HOST, PORT_NUMBER);
    	HTMLParser parser = new HTMLParser(c);
    	
    	
    	
//        	c.makeConnection(HOST, PORT_NUMBER);
        	urls = parser.collectRelativeURLs(HOST);
        	docs = parser.buildDocs(urls);
//        	for(Document doc: docs) {
//        		System.out.println(doc.);
//        	}
        	//while the set contains relative urls
        		//make get requests and write html files to file system
        	
//    	} catch (IOException e) {
//    		e.printStackTrace();
//    	} 
    }

    public static void main(String args[]){
    	App app = new App();
    	app.crawl();
    }
}
