/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spider2;

import java.io.IOException;
import java.util.Set;
import java.util.HashSet;
import java.util.List;
import java.util.ArrayList;
import org.jsoup.nodes.*;


public class App {
    

    public static final String HOST = "smt-stage.qa.siliconmtn.com";
    public static final int PORT_NUMBER = 443;
    
    private List<Document> docs = null;
	private Set<String> urls = null;
	
	Parser parser;


    public static void main(String args[]){
    	App app = new App();
    	//app.crawl();
    	app.enterAdmin();
    }
    
    /** First half of the assignment connects 
     * 
     */
    public void crawl() {
    	Connector connection = new Connector(HOST, PORT_NUMBER);
    	parser = new Parser();
    	
    	String baseHTML = connection.getHTML(HOST, PORT_NUMBER, "/");
    	
    	urls = parser.collectRelativeURLs(baseHTML);
    	docs = connection.buildDocs(urls);

    	//parser.documentToFile(docs); this is correct
    }
    
    public void enterAdmin() {
    	Connector connection = new Connector(HOST, PORT_NUMBER);
    	parser = new Parser();
    	
    	String html = connection.postRequest(HOST, PORT_NUMBER);
    	//I have cookies saved in Connector need to crawl thru the admin site while passing these cookies
    }

}
