/*
  * This Java source file was generated by the Gradle 'init' task.
 */
package spider2;
import java.io.*;
import java.net.Socket;

import javax.net.ssl.*;


/****************************************************************************
 * <b>Title:</b> Connection.java
 * <b>Project:</b> Spider
 * <b>Description:</b> Class to make client-server connection via a socket
 * with input and output streams
 * 
 * 
 * <b>Copyright:</b> Copyright (c) 2023
 * <b>Company:</b> Silicon Mountain Technologies
 * 
 * @author Evan Swett
 * @version 3.0
 * @since April 4, 2023
 * <b>updates:</b>
 * 
 ****************************************************************************/

public final class Connection {
	
    BufferedReader in = null;
    DataOutputStream out = null;
    
    SSLSocket socket = null; // how come this is not used?
    
    Connection(String host, int portNumber) {

    	SSLSocketFactory factory = (SSLSocketFactory) SSLSocketFactory.getDefault();

    	try {
    		socket = (SSLSocket) factory.createSocket(host, portNumber);
    		in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
    		out = new DataOutputStream(socket.getOutputStream());
    		System.out.println("Socket made");
    	} catch (IOException e) {
    		e.printStackTrace();
    	}
    }
    
    public Socket getSocket() {
    	return socket;
    }
    
//    
//    public boolean makeConnection(String host, int portNumber) throws IOException {
//    	
//    	SSLSocketFactory factory = (SSLSocketFactory) SSLSocketFactory.getDefault();
//    	
//    	try {
//    		socket = (SSLSocket) factory.createSocket(host, portNumber);
//    		in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
//    		out = new DataOutputStream(socket.getOutputStream());
//    		System.out.println("Socket made");
//    	} catch (IOException e) {
//    		e.printStackTrace();
//      		return false;
//    	}
//    	return true;
//    }
}
